# required to get an OSX environment
language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"

  # Get hold of ANT.
  #- brew update
  - brew install ant

  # Grab Flex SDK
  - curl -L https://bitbucket.org/nguyenbs/air-sdks/raw/3f2fd74094c2343b996f06e92699a56c8c9c6113/air_sdk_28.blob > sdk.zip
  - unzip sdk.zip -d ./sdk
  - export "SDK_HOME=`pwd`/sdk"

  # Download and install a specific Flash Player from the Adobe Archives:
  # https://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html
  - sh getFpFromArchive.sh 'https://bitbucket.org/nguyenbs/air-sdks/raw/fcb84a7ffac3ba5b0a8b1a3072e7915b3fb30b8f/fp_28.0.0.161_archive.zip'
  - export FLASH_CMD="`pwd`/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"

script: ant test -DFLASH_PLAYER_CMD="${FLASH_PLAYER_CMD}"